### ISSUE TITLE
unable to run Scripts

### ISSUE THREAD

**Issue by maorkuriel** [thesecuresoftwarefactory/ssf#26]
** Question **
I am running the 00-kubernetes-minikube-setup script and getting the following error:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

after running xcode-select --install, the script ran with no issues

Similar issue when running 20-spire-setup script, only after running gen-keys script the script completed with no issues.

This was not listed in the prerequisites, so I want to check if this is something that I missed or this should be added in the README.md File.

** Additional Context **

**Comment by mlieberman85** [comment]
I don't have m1 mac, but I think @trmiller @bradbeck and @rgreinho do.

**Comment by bradbeck** [comment]
Yeah, we currently assume that brew is installed and typically that requires that Xcode command-line tools are installed, but we could be more explicit about that.

I haven't run across the need to run `kubernetes/scripts/gen-keys.sh` independently in order to get `20-spire-setup.sh` to complete successfully. Recent changes have introduced a couple of `wait_for_pods` calls to help stabilize that script. We may still need to introduce a sleep before the last `kubectl exec ...` to stabilize the "clean install" scenario.
